{
 "title": "Spinnaker Pipeline Metrics",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Executive High Level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Pipelines By Provider",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cloud_provider) (spinnaker_execution_starting_total{event_source=\"orca\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipelines By Region",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cloud_region) (spinnaker_execution_starting_total{event_source=\"orca\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipelines By Domain",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cloud_domain) (spinnaker_execution_starting_total{event_source=\"orca\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipelines By Environment",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cloud_env) (spinnaker_execution_starting_total{event_source=\"orca\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DORA Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Change Failure Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spinnaker_execution_incomplete) / (sum(spinnaker_execution_incomplete) + sum(spinnaker_execution_completed)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean Time To Repair",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n  spinnaker_last_success_ts_seconds{event_source=\"orca\"} \n  - spinnaker_last_failure_ts_seconds{event_source=\"orca\"},\n  0\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average LTFC By Pipeline",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(spinnaker_pipeline_complete_duration_seconds{execution_status=\"SUCCEEDED\"}[$__range])",
     "legendFormat": "{{execution_name}}"
    }
   ]
  },
  {
   "title": "Deployment Frequency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Pipeline Completed Duration ",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(spinnaker_pipeline_complete_duration_seconds{execution_status=\"SUCCEEDED\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Pipeline Failed Duration ",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(spinnaker_pipeline_incomplete_duration_seconds{execution_status=\"TERMINAL\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Pipeline Canceled Duration ",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(spinnaker_pipeline_incomplete_duration_seconds{execution_status=\"CANCELED\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "P95 PIpeline Execution Duration",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "quantile_over_time( 0.95, (spinnaker_pipeline_complete_duration_seconds{execution_status=\"SUCCEEDED\"}[$__range]) )",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Monthly Executions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (bucket, execution_status) (label_replace(rate(spinnaker_pipeline_executions_total[28d]), \"bucket\", \"last24h\", \"\", \"\"))",
     "legendFormat": "{{execution_status}}"
    }
   ]
  },
  {
   "title": "Weekly Executions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (bucket, execution_status) (label_replace(rate(spinnaker_pipeline_executions_total[7d]), \"bucket\", \"last24h\", \"\", \"\"))",
     "legendFormat": "{{execution_status}}"
    }
   ]
  },
  {
   "title": "Daily Executions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (bucket, execution_status) (label_replace(rate(spinnaker_pipeline_executions_total[24h]), \"bucket\", \"last24h\", \"\", \"\"))",
     "legendFormat": "{{execution_status}}"
    }
   ]
  },
  {
   "title": "Hourly Executions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (bucket, execution_status) (label_replace(rate(spinnaker_pipeline_executions_total[1h]), \"bucket\", \"last24h\", \"\", \"\"))",
     "legendFormat": "{{execution_status}}"
    }
   ]
  },
  { "title": "Global Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Execution By Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "expr": "count by (execution_status) (\n  sum_over_time(\n    rate(spinnaker_pipeline_executions_total[$__rate_interval])[ $__range : $__interval ]\n  )\n)\n",
     "legendFormat": "{{execution_status}}",
     "queryMode": "expression",
     "rawSql": "count by (execution_status) (\n  max_over_time(\n    spinnaker_pipeline_executions_total{execution_application=~\".*\"}[$__range]\n  )\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Pipeline Stages By Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (stage_type) (spinnaker_stage_starting_total{event_source=\"orca\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Pipeline Executions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,\n  max by (execution_application, execution_name)\n    (spinnaker_pipeline_complete_duration_seconds)\n)",
     "legendFormat": "{{execution_name}}"
    }
   ]
  },
  {
   "title": "Execution By Trigger Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (execution_triggertype) (spinnaker_execution_completed{event_source=\"orca\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution By Trigger User",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (execution_user) (spinnaker_execution_completed{event_source=\"orca\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 LTFC By Pipeline",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(\n  0.95,\n  spinnaker_pipeline_complete_duration_seconds{execution_status=\"SUCCEEDED\"}[$__range]\n)",
     "legendFormat": "{{execution_name}}"
    }
   ]
  },
  {
   "title": "Pipeline Cancellation Reasons",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (execution_cancelreason) (spinnaker_execution_failed_total{event_source=\"orca\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Stage Failure Reasons",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (stage_exceptiontype) (spinnaker_stage_failed_total{event_source=\"orca\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pipeline Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Pipelines Starting",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (execution_application) (spinnaker_execution_starting_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipelines Completed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (execution_application) (spinnaker_execution_completed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipelines Failed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (execution_application) (spinnaker_execution_failed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Stage Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Stages Starting",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (execution_application) (spinnaker_stage_starting_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stages Complete",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (execution_application) (spinnaker_stage_completed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stages Failed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (execution_application) (spinnaker_stage_failed_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}